# Site settings
title: London - Paris
description: > # this means to ignore newlines until "baseurl:"
  Þessi síða er tileinkuð mikilli svaðilför sem við vinir lögðum í sumarið 2014, hjólatúr frá Lundunum til Parísar.
baseurl: "/london-paris" # the subpath of your site, e.g. /blog/
url: "http://ragnaringi.github.com/london-paris" # the base hostname & protocol for your site
twitter_username: ragnaringi
github_username:  ragnaringi

# Build settings
markdown: kramdown
